### ISSUE TITLE
Support with PHP8.1

### ISSUE THREAD

**Issue by chenly** [dimabdc/PHP-Fast-Simple-HTML-DOM-Parser#10]
`2022-12-15T13:30:31.799 app[96abb1ce] iad [info] #14 {main} in /usr/src/myapp/vendor/dimabdc/php-fast-simple-html-dom-parser/lib/Element.php on line 30

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] Worker[531] process terminated with ERROR: E_ERROR "During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of FastSimpleHTMLDom\Element::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/src/myapp/vendor/dimabdc/php-fast-simple-html-dom-parser/lib/Element.php:508

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] Stack trace:

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] #0 /usr/src/myapp/vendor/dimabdc/php-fast-simple-html-dom-parser/lib/Element.php(30): {closure}(8192, 'Return type of ...', '/usr/src/myapp/...', 508)

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] #1 /usr/src/myapp/vendor/composer/ClassLoader.php(571): include('/usr/src/myapp/...')

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] #2 /usr/src/myapp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/usr/src/myapp/...')

2022-12-15T13:30:31.799 app[96abb1ce] iad [info] #3 /usr/src/myapp/vendor/dimabdc/php-fast-simple-html-dom-parser/lib/Document.php(161): Composer\Autoload\ClassLoader->loadClass('FastSimpleHTMLD...')`

**Comment by chenly** [comment]
Return type should either be compatible with IteratorAggregate::getIterator(): Traversable, 
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
